# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: DSCR_FileContent/TextFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.gitconfig"
        Contents: |
          [core]
          autocrlf=true
          longpaths=true
          editor=code --wait

          [user]
          name=harrhp
          email=<>

          [diff]
          tool=vscode

          [difftool "vscode"]
          cmd=code --wait --diff $LOCAL $REMOTE

          [merge]
          tool=vscode
          guitool=vscode

          [mergetool "vscode"]
          cmd=code --wait $MERGED

          [init]
          defaultBranch=main

          [includeIf "gitdir:~/**/work/"]
          path = ~/.work.gitconfig
        NewLine: LF
  configurationVersion: 0.2.0
