# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: pwsh
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: xPSDesiredStateConfiguration/xRegistry
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Key: HKLM:\SOFTWARE\OpenSSH
        ValueName: DefaultShell
        ValueData: 'C:\Program Files\PowerShell\7\pwsh.exe'
        Force: true
      dependsOn:
        - pwsh
  configurationVersion: 0.2.0
