# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: ComputerManagementDsc/Computer
      directives:
        description: rename computer
        allowPrerelease: true
      settings:
        Name: lenovo
  configurationVersion: 0.2.0
