# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.Aliae
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.OpenSSH.Beta
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: gerardog.gsudo
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JetBrains.Toolbox
        source: winget
  configurationVersion: 0.2.0
