# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: pwsh
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: DSCR_FileContent/TextFile
      directives:
        allowPrerelease: false
      settings:
        Ensure: Present
        Path: "~/Desktop/lights out.bat"
        Contents: "pwsh.exe -File ${WingetConfigRoot}/lights-out.ps1"
        NewLine: CRLF
      dependsOn:
        - pwsh
  configurationVersion: 0.2.0
