# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: ComputerManagementDsc/TimeZone
      directives:
        allowPrerelease: true
      settings:
        IsSingleInstance: yes
        TimeZone: Russian Standard Time
  configurationVersion: 0.2.0
