# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: xRobocopy/xRobocopy
      id: pwsh-module
      directives:
        description: deploy powershell module
        allowPrerelease: true
      settings:
        Source: ${WingetConfigRoot}/../powershell/modules/LightsOut
        Destination: C:\Program Files\WindowsPowerShell\Modules\LightsOut
        Retry: 1
        Wait: 1
        AdditionalArgs: /MIR
    - resource: DSCR_FileContent/TextFile
      directives:
        allowPrerelease: false
      settings:
        Ensure: Present
        Path: "~/Desktop/lights out.bat"
        Contents: "pwsh.exe -c LightsOut"
        NewLine: CRLF
  configurationVersion: 0.2.0
