# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.Windows.Developer/UserAccessControl
      directives:
        allowPrerelease: true
      settings:
        AdminConsentPromptBehavior: NoCredOrConsentRequired
  configurationVersion: 0.2.0
