# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.Aliae
        source: winget
    - resource: DSCR_FileContent/TextFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
        Contents: |
          $env:ALIAE_CONFIG = "https://raw.githubusercontent.com/harrhp/configuration/HEAD/shell/aliae.yaml";
          aliae init pwsh | Invoke-Expression
        NewLine: LF
  configurationVersion: 0.2.0
