# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: ComputerManagementDsc/Computer
      directives:
        description: rename computer
        allowPrerelease: true
      settings:
        Name: desktop
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget
  configurationVersion: 0.2.0
