# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: MyResources/Printer
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Name: Xerox Phaser 3020
    - resource: MyResources/PrinterPort
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Name: Xerox Phaser 3020 TCPIP
    - resource: MyResources/PrinterDriver
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Name: Xerox Phaser 3020 XPS
    - resource: MyResources/WindowsDriver
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Inf: sxj2xv4.inf
    - resource: MyResources/WindowsDriver
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Inf: sxj2m.inf
    - resource: MyResources/WindowsDriver
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        Ensure: Absent
        Inf: sxj2x.inf
  configurationVersion: 0.2.0
