# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "7zip.7zip"
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: gerardog.gsudo
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: AntibodySoftware.WizTree
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: Git.Git
        source: winget
    - resource: MyResources/File
      directives:
        description: configure git
        allowPrerelease: true
      settings:
        Ensure: Present
        SourcePath: ${WingetConfigRoot}/../../files/.gitconfig
        DestinationPath: ~/.gitconfig
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: aliae
      directives:
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.Aliae
        source: winget
    - resource: xPSDesiredStateConfiguration/xEnvironment
      directives:
        description: opt out of powershell telemetry
        securityContext: elevated
      settings:
        Ensure: Present
        Name: POWERSHELL_TELEMETRY_OPTOUT
        Value: true
        Target: Machine
    - resource: xPSDesiredStateConfiguration/xMsiPackage
      directives:
        description: install powershell
        securityContext: elevated
      settings:
        Ensure: Present
        ProductId: "{18AF003E-70BD-4CD0-874C-D53E4D0B9708}"
        Path: https://github.com/PowerShell/PowerShell/releases/download/v7.6.0/PowerShell-7.6.0-win-x64.msi
        HashAlgorithm: SHA256
        FileHash: CE60D76319739B52B281C744144CD8E942AED9CDA02483CE9BD732E140F75982
    - resource: MyResources/File
      directives:
        description: configure pwsh profile
        allowPrerelease: true
      settings:
        Ensure: Present
        SourcePath: ${WingetConfigRoot}/../../files/Microsoft.PowerShell_profile.ps1
        DestinationPath: ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1
    - resource: xPSDesiredStateConfiguration/xScript
      directives:
        description: reload path
        allowPrerelease: true
      settings:
        GetScript: state
        TestScript: $false
        SetScript: $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User");
    - resource: xPSDesiredStateConfiguration/xScript
      directives:
        description: install fonts
        allowPrerelease: true
      settings:
        GetScript: state
        TestScript: $false
        SetScript: oh-my-posh font install CascadiaCode
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wt
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: MyResources/File
      directives:
        description: configure windows terminal
        allowPrerelease: true
      settings:
        Ensure: Present
        SourcePath: ${WingetConfigRoot}/../../files/windows-terminal-settings.json
        DestinationPath: ~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: Microsoft.OpenSSH.Preview
        source: winget
  configurationVersion: 0.2.0
