# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: MyResources/File
      directives:
        description: scratchpad
        allowPrerelease: true
      settings:
        Ensure: Present
  configurationVersion: 0.2.0
