# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: DSCR_FileContent/TextFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
        Contents: |
          {
            "$help": "https://aka.ms/terminal-documentation",
            "$schema": "https://aka.ms/terminal-profiles-schema",
            "actions": [
              {
                "command": "unbound",
                "keys": "ctrl+w"
              },
              {
                "command": "unbound",
                "keys": "ctrl+shift+w"
              },
              {
                "command": "unbound",
                "keys": "ctrl+shift+c"
              },
              {
                "command": "unbound",
                "keys": "ctrl+insert"
              },
              {
                "command": "unbound",
                "keys": "enter"
              },
              {
                "command": "unbound",
                "keys": "ctrl+shift+v"
              },
              {
                "command": "unbound",
                "keys": "shift+insert"
              },
              {
                "command": "unbound",
                "keys": "ctrl+shift+a"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+1"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+2"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+3"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+4"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+5"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+6"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+7"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+8"
              },
              {
                "command": "unbound",
                "keys": "ctrl+alt+9"
              },
              {
                "command": "unbound",
                "keys": "ctrl+shift+t"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 0
                },
                "keys": "ctrl+1"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 1
                },
                "keys": "ctrl+2"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 2
                },
                "keys": "ctrl+3"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 3
                },
                "keys": "ctrl+4"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 4
                },
                "keys": "ctrl+5"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 5
                },
                "keys": "ctrl+6"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 6
                },
                "keys": "ctrl+7"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 7
                },
                "keys": "ctrl+8"
              },
              {
                "command": {
                  "action": "switchToTab",
                  "index": 8
                },
                "keys": "ctrl+9"
              },
              {
                "command": "closePane",
                "keys": "ctrl+w"
              },
              {
                "command": {
                  "action": "copy"
                },
                "keys": "ctrl+c"
              },
              {
                "command": "paste",
                "keys": "ctrl+v"
              },
              {
                "command": {
                  "action": "newTab"
                },
                "keys": "ctrl+t"
              },
              {
                "command": "find",
                "keys": "ctrl+f"
              },
              {
                "command": "toggleSplitOrientation",
                "keys": "ctrl+alt+t"
              },
              {
                "command": {
                  "action": "swapPane",
                  "direction": "down"
                },
                "keys": "ctrl+shift+down"
              },
              {
                "command": {
                  "action": "swapPane",
                  "direction": "up"
                },
                "keys": "ctrl+shift+up"
              },
              {
                "command": {
                  "action": "swapPane",
                  "direction": "left"
                },
                "keys": "ctrl+shift+left"
              },
              {
                "command": {
                  "action": "swapPane",
                  "direction": "right"
                },
                "keys": "ctrl+shift+right"
              },
              {
                "command": "selectAll",
                "keys": "ctrl+a"
              }
            ],
            "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "firstWindowPreference": "defaultProfile",
            "launchMode": "default",
            "newTabMenu": [
              {
                "type": "remainingProfiles"
              }
            ],
            "profiles": {
              "defaults": {
                "bellStyle": "none",
                "colorScheme": "Seafoam Pastel",
                "cursorColor": "#FFFFFF",
                "font": {
                  "face": "CaskaydiaCove Nerd Font Mono",
                  "size": 11.0
                }
              },
              "list": [
                {
                  "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                  "hidden": false,
                  "name": "PowerShell",
                  "source": "Windows.Terminal.PowershellCore"
                },
                {
                  "commandline": "wsl -d UbuntuDev pwsh",
                  "guid": "{22e51f07-52ff-4d5f-bf1d-4f2e8a59d851}",
                  "hidden": false,
                  "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
                  "name": "UbuntuDev",
                  "startingDirectory": "~"
                },
                {
                  "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                  "hidden": false,
                  "name": "cmd"
                }
              ]
            },
            "schemes": [
              {
                "background": "#243939",
                "black": "#757575",
                "blue": "#4D7B82",
                "brightBlack": "#8A8A8A",
                "brightBlue": "#7AC3CF",
                "brightCyan": "#ADE0E0",
                "brightGreen": "#98D9AA",
                "brightPurple": "#D6B2A1",
                "brightRed": "#CF937A",
                "brightWhite": "#E0E0E0",
                "brightYellow": "#FAE79D",
                "cursorColor": "#FFFFFF",
                "cyan": "#729494",
                "foreground": "#D4E7D4",
                "green": "#728C62",
                "name": "Seafoam Pastel",
                "purple": "#8A7267",
                "red": "#825D4D",
                "selectionBackground": "#FFFFFF",
                "white": "#E0E0E0",
                "yellow": "#ADA16D"
              }
            ],
            "showTabsInTitlebar": true,
            "showTerminalTitleInTitlebar": true,
            "theme": "system",
            "themes": [],
            "useAcrylicInTabRow": false
          }
        NewLine: LF
  configurationVersion: 0.2.0
