# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: ComputerManagementDsc/UserAccountControl
      directives:
        allowPrerelease: true
      settings:
        IsSingleInstance: yes
        NotificationLevel: NeverNotify
  configurationVersion: 0.2.0
