# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: JetBrains.Toolbox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.WSL
        source: winget
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: experimental
        Key: autoMemoryReclaim
        Value: dropcache
        NewLine: LF
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: experimental
        Key: sparseVhd
        Value: "true"
        NewLine: LF
    - resource: MyResources/File
      directives:
        description: UbuntuDev cloud-init
        allowPrerelease: true
      settings:
        Ensure: Present
        SourcePath: ${WingetConfigRoot}/cloud-config.yaml
        DestinationPath: ~/.cloud-init/UbuntuDev.user-data
    - resource: MyResources/WslDistro
      directives:
        description: install ubuntu
        allowPrerelease: true
      settings:
        Ensure: Present
        Distro: UbuntuDev
        InstallLocation: ~/dev/wsl/distro/UbuntuDev
        File: https://cloud-images.ubuntu.com/wsl/noble/current/ubuntu-noble-wsl-amd64-ubuntu.rootfs.tar.gz
  configurationVersion: 0.2.0
