# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.WSL
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        allowPrerelease: true
      settings:
        id: Docker.DockerCLI
        source: winget
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: experimental
        Key: autoMemoryReclaim
        Value: dropcache
        NewLine: LF
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: experimental
        Key: sparseVhd
        Value: "true"
        NewLine: LF
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: general
        Key: instanceIdleTimeout
        Value: "-1"
        NewLine: LF
    - resource: DSCR_FileContent/IniFile
      directives:
        allowPrerelease: true
      settings:
        Ensure: Present
        Path: "~/.wslconfig"
        Section: wsl2
        Key: networkingMode
        Value: mirrored
        NewLine: LF
    - resource: MyResources/File
      directives:
        description: devbox cloud-init
        allowPrerelease: true
      settings:
        Ensure: Present
        SourcePath: ${WingetConfigRoot}/cloud-config.yaml
        DestinationPath: ~/.cloud-init/devbox.user-data
    - resource: MyResources/WslDistro
      directives:
        description: install ubuntu
        allowPrerelease: true
      settings:
        Ensure: Present
        Distro: devbox
        InstallLocation: ~/dev/wsl/distro/devbox
        File: https://cdimages.ubuntu.com/ubuntu-wsl/noble/daily-live/current/noble-wsl-amd64.wsl
  configurationVersion: 0.2.0
